import { zipSync } from 'fflate';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

import { DEFAULT_BUNDLE_BINARIES, MKCERT_TARGETS } from '../consts.js';
import { fetchAndCacheMkcertBinaries } from '../mkcert/fetchAndCacheMkcertBinaries.js';
import { fetchLatestMkcertReleaseAssets } from '../mkcert/fetchLatestMkcertReleaseAssets.js';
import { debugLog } from '../utils/debug.js';
import { getArchiveInstructions } from './getArchiveInstructions.js';

/**
 * Build the in-memory host helper bundle: one zip archive containing root CA files and install scripts.
 *
 * @param {Object} params
 * @param {boolean} [params.bundleBinaries=DEFAULT_BUNDLE_BINARIES] Whether to bundle pre-downloaded platform `mkcert` binaries into the archive.
 * @param {string} params.projectName Name of the project used in generated archive filename.
 * @param {string} params.savePath Path to directory containing root CA certificates.
 * @returns {Promise<{ archiveBuffer: Buffer, archiveContents: string[], archiveFileName: string }>} Bundle details including zip buffer and file listings.
 */
export async function createHostTrustArchive({ bundleBinaries = DEFAULT_BUNDLE_BINARIES, projectName, savePath }) {
    debugLog(`Creating host trust archive (bundleBinaries=${bundleBinaries}, projectName="${projectName}").`);

    const formattedTimestamp = new Date()
        .toISOString()
        .replaceAll(':', '-') // Colons are not allowed in `Windows` file names.
        .replaceAll(/\.\d+/g, ''); // Remove milliseconds for better readability.
    const archiveFileName = `${projectName}-CA-${formattedTimestamp}.zip`;

    const staticDir = '#src/static';
    const staticDirUrl = new URL(import.meta.resolve(staticDir));
    const staticDirEntries = await readdir(staticDirUrl, { withFileTypes: true });
    const staticFiles = staticDirEntries.filter(entry => entry.isFile());

    const archiveFiles = await Promise.all(
        staticFiles.map(async entry => ({
            content: await readFile(new URL(import.meta.resolve(`${staticDir}/${entry.name}`))),
            name:    entry.name,
        })),
    );

    const rootCaPem = await readFile(path.join(savePath, 'rootCA.pem'), 'utf8').catch(() => null);

    // Strict validation: an archive without `rootCA.pem` will cause host installers to fail or generate un-trusted local certificates.
    // If `mkcert` failed inside the container or `savePath` is invalid, abort archive creation with an explicit error.
    if (!rootCaPem) {
        throw new Error(`[vite-plugin-mkcert-containerized] Missing "rootCA.pem" certificate in "${savePath}". Ensure \`mkcert\` has generated root CA certificates.`);
    }

    const hostTrustInstructions = getArchiveInstructions({ bundleBinaries });

    archiveFiles.push(
        {
            content: Buffer.from(rootCaPem, 'utf8'),
            name:    'rootCA.pem',
        },
        {
            content: Buffer.from(hostTrustInstructions),
            name:    'INSTRUCTIONS.txt',
        },
    );

    if (bundleBinaries) {
        debugLog('Fetching platform mkcert binaries to bundle into archive...');
        const binaries = await fetchAndCacheMkcertBinaries();
        archiveFiles.push(...binaries);
    }
    else {
        debugLog('Fetching latest mkcert release assets metadata for dynamic download URLs...');
        const releaseAssets = await fetchLatestMkcertReleaseAssets();
        const envContent = [
            '# Generated by vite-plugin-mkcert-containerized',
            ...MKCERT_TARGETS.map(target => `${target.envKey}=${releaseAssets.downloadUrls[target.binaryKey] ?? ''}`),
            '',
        ].join('\n');

        archiveFiles.push({
            content: Buffer.from(envContent),
            name:    'mkcert-containerized.env',
        });
    }

    const archiveEntries = Object.fromEntries(archiveFiles.map(file => [file.name, file.content]));
    const archiveBuffer = Buffer.from(zipSync(archiveEntries, { level: 0 }));

    const archiveContents = archiveFiles.map(file => file.name);

    debugLog(`Archive "${archiveFileName}" generated with ${archiveContents.length} files (${archiveBuffer.length} bytes).`);

    return {
        archiveBuffer,
        archiveContents,
        archiveFileName,
    };
}
