import { DEFAULT_BUNDLE_BINARIES } from '../consts.js';

/**
 * Build the human-readable archive instructions bundled with the host trust ZIP.
 *
 * @param {Object} [params]
 * @param {boolean} [params.bundleBinaries=DEFAULT_BUNDLE_BINARIES] Whether the archive includes pre-bundled `mkcert` binaries.
 * @returns {string} Instruction text.
 */
export function getArchiveInstructions({ bundleBinaries = DEFAULT_BUNDLE_BINARIES } = {}) {
    return [
        'mkcert Host Trust Helper',
        '========================',
        '',
        `This archive contains the Root CA certificate generated inside your dev container, along with helper scripts ${bundleBinaries ? 'and pre-bundled mkcert binaries to install and trust it on your host machine offline.' : 'to install and trust it on your host machine.'}`,
        '',
        'INSTRUCTIONS',
        '------------',
        '1. Extract all contents of this ZIP archive to a folder on your host machine.',
        '2. Run the script corresponding to your host operating system:',
        '   - Windows (Command Prompt): Run `install-rootCA.cmd`',
        '   - Windows (PowerShell): Run `install-rootCA.ps1`',
        '   - macOS / Linux: Run `chmod +x install-rootCA.sh && ./install-rootCA.sh`',
        '',
        'UNINSTALLATION',
        '--------------',
        'To remove the Root CA from your host trust store in the future, run the matching `uninstall-rootCA` script.',
        '',
        'FILES INCLUDED',
        '--------------',
        '- rootCA.pem: Root CA certificate generated by mkcert.',
        bundleBinaries
            ? '- mkcert-*: Pre-bundled mkcert binaries for macOS, Linux, and Windows.'
            : '- mkcert-containerized.env: Environment metadata containing mkcert download URLs for the helper scripts.',
        '- install-rootCA.*: Installs `rootCA.pem` using the bundled or downloaded `mkcert` binary.',
        '- uninstall-rootCA.*: Removes `rootCA.pem` from the host trust store using the bundled or downloaded `mkcert` binary.',
        '- manage-rootCA.*: Internal helpers used by the install and uninstall entrypoints.',
        '',
    ].join('\n');
}
